import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider
} from '@clerk/nextjs'

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create  App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
	<ClerkProvider>
		<html lang="en">
			<body
				className={`antialiased`}
			>
				<div className="w-1/5 h-screen bg-gray-50">
				{/* <Navibar></Navibar> */}
				</div>
				<div className="w-4/5 h-screen"></div>
				{children}
			</body>
			</html>
	</ClerkProvider>
    
  );
}
